/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface QueryResult {
  rows: Array<Array<JsValueWrapper>>
  columns: Array<ColumnInfo>
  rowCount: number
}
export interface ColumnInfo {
  name: string
  type: string
}
export declare class Client {
  constructor(connectionString: string)
  connect(): Promise<void>
  query(sql: string, params?: Array<JsValueWrapper> | undefined | null): Promise<QueryResult>
  execute(sql: string, params?: Array<JsValueWrapper> | undefined | null): Promise<number>
  close(): Promise<void>
  /** Alias for close() */
  end(): Promise<void>
  /** Fast query returning binary-encoded buffer for JS-side decoding */
  queryRaw(sql: string, params?: Array<JsValueWrapper> | undefined | null): Promise<Buffer>
}
